version: '2'
services:
    projetofinaljdlteste-app:
        image: projetofinaljdlteste
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://projetofinaljdlteste-mysql:3306/projetofinaljdlteste?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://projetofinaljdlteste-elasticsearch:9200
        ports:
            - 8080:8080
    projetofinaljdlteste-mysql:
        extends:
            file: mysql.yml
            service: projetofinaljdlteste-mysql
    projetofinaljdlteste-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: projetofinaljdlteste-elasticsearch
